plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

if (System.getenv('MOD_VERSION') != null) {
    mod_version = System.getenv('MOD_VERSION')
}
version = mod_version
group = 'com.klikli_dev'

sourceSets.main.resources {
    srcDir('src/generated/resources')
}

base {
    archivesName = "${mod_id}-${minecraft_version}-neoforge"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)
java.withSourcesJar()

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArguments.add "--username=Dev"
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            logLevel = org.slf4j.event.Level.DEBUG
            jvmArguments.addAll('-XX:+AllowEnhancedClassRedefinition', '-XX:+IgnoreUnrecognizedVMOptions')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly "com.klikli_dev:occultism-${minecraft_version}-neoforge:${occultism_version}"
    localRuntime "com.klikli_dev:occultism-${minecraft_version}-neoforge:${occultism_version}"

    compileOnly("dev.latvian.mods:kubejs-neoforge:${kubejs_version}") {
        exclude group: 'dev.latvian.mods', module: 'better-advanced-tooltips'
    }
    localRuntime("dev.latvian.mods:kubejs-neoforge:${kubejs_version}") {
        exclude group: 'dev.latvian.mods', module: 'better-advanced-tooltips'
    }

    compileOnly("dev.latvian.mods:better-advanced-tooltips:2601.1.0-build.9")
    localRuntime("dev.latvian.mods:better-advanced-tooltips:2601.1.0-build.9")

    localRuntime("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    localRuntime("top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}") { transitive = false }
}

repositories {
    maven {
        url = "https://maven.neoforged.net/releases/"
        content {
            includeGroupByRegex("net\\.neoforged.*")
        }
    }
    maven {
        url "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"
        content {
            includeGroup "com.klikli_dev"
        }
    }
    maven {
        name = 'GeckoLib Maven'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup "com.geckolib"
        }
    }
    maven {
        name = "Curios Maven"
        url = "https://maven.theillusivec4.top/"
        content {
            includeGroup "top.theillusivec4.curios"
        }
    }
    maven {
        name = 'JEI Maven'
        url = 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }
    maven {
        name = "Kubejs"
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    maven {
        name = "Architectory (for Kubejs)"
        url "https://maven.architectury.dev/"
        content {
            includeGroup "dev.architectury"
        }
    }
    maven {
        url 'https://jitpack.io'
        content {
            includeGroup "com.github.rtyley"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_loader_version_range: neo_loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            kubejs_version         : kubejs_version,
            kubejs_version_range   : kubejs_version_range,
            occultism_version      : occultism_version,
            occultism_version_range: occultism_version_range,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()

            from components.java

            pom {
                name = mod_name
                description = "${mod_description}"
                url = 'https://github.com/klikli-dev/occultism-kubejs'
                licenses {
                    license {
                        name = 'MIT'
                        url = 'https://github.com/klikli-dev/occultism-kubejs#licensing'
                    }
                }
                scm {
                    connection = 'scm:git:ssh:git@github.com:klikli-dev/occultism-kubejs.git'
                    url = 'https://github.com/klikli-dev/occultism-kubejs'
                }
            }
        }
    }
    repositories {
        maven {
            name = "cloudsmith"
            url = "https://maven.cloudsmith.io/klikli-dev/mods/"
            def releasesRepoUrl = "https://maven.cloudsmith.io/klikli-dev/mods/"
            def snapshotsRepoUrl = "https://maven.cloudsmith.io/klikli-dev/mods/"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username = System.getenv('MAVEN_USER')
                password = System.getenv('MAVEN_PASS')
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

afterEvaluate {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "2000"
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
